name: run-tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [8.2, 8.1]
        laravel: [9.*]
        stability: [prefer-stable]
        include:
#           - laravel: 10.*
#             testbench: 8.*
#             pest: 2.*
#             pest-plugin-arch": 2.*
#             pest-plugin-laravel: 2.*
          - laravel: 9.*
            testbench: 7.*
            pest: 1.*
            pest-plugin-arch": 1.*
            pest-plugin-laravel: 1.*

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, dom, gd, json, libxml, mbstring, zip
          coverage: none

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}"
          composer require --dev "orchestra/testbench:${{ matrix.testbench }}"
          composer require "pestphp/pest:^${{ matrix.pest }}"
          composer require "pestphp/pest-plugin-arch:^${{ matrix.pest-plugin-arch }}"
          composer require "pestphp/pest-plugin-laravel:^${{ matrix.pest-plugin-laravel }}"
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: List Installed Dependencies
        run: composer show -D

      - name: Execute tests
        run: vendor/bin/pest
